### ISSUE TITLE
Create a plan for the games 'Scene' architecture

### ISSUE THREAD

**Issue by baconeta** [Baconeta-Studios/setting-the-stage#10]
There is a lot that needs to go into this task and probably it will rely heavily on #6 and #7 before it can really be ready but even a draft is a good idea based on the prototype gamejam version and what difficulties we already ran into there.

**Comment by SabrinaTheCookie** [comment]
- **MainMenu**
- **Act 1..x**
   - _Contains references to which Chapter is currently underway, as well as Act Cutscenes._
   - **Chapter 1..x**
     - _Main game flow._
- **Game Instance**
  - _Is always loaded._
  - _Contains scene management, Game Save, (And maybe audio?)_

So from the Main Menu we'd load an Act, which depending on your selection will load a Chapter (Instead of Night?) as an Additive Scene.

**Comment by baconeta** [comment]
I'm happy for scene templating. I think it'll work okay for a template system as well. I definitely like a system like what we had in the jam, where we inject and extract data from a standard scene but it's up to you and if you think another option works well, I'm down for it. I'll let you handle the decision making in that, so long as its documented well, I don't really mind .

**Comment by SabrinaTheCookie** [comment]
I think what we had in the jam worked, but on a larger scale i think it will make challenges in iteration and for artists to understand/participate. If every scene has a different layout and art assets then it may get too complex for a single scene.

**Comment by SabrinaTheCookie** [comment]
Scene Templates aren't what I thought so don't worry about that, we'll keep it simple and do what we had for the jam - Ill close this ticket and create a new one for building out the scenes. I've added the scene architecture to the Game Flow because I can't edit the Drive, would you give me edit permissions?
